version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: carrentals
