version: "3"
name: rentacar
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - rent-a-car-mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: carrentals

volumes:
  rent-a-car-mysql-data:
