version: "3"
name: rentacar
services:
  app:
    image: php:8.3-apache
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html

    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - rent-a-car-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  rent-a-car-mysql-data:
